### ISSUE TITLE
CMAKE ERROR 

### ISSUE THREAD

**Issue by Pan-long-ming** [ntnu-arl/rovtio#2]
When i run this command "catkin build rovtio --cmake-args -DCMAKE_BUILD_TYPE=Release -DMAKE_SCENE=OFF -DROVIO_NCAM=2 -DROVIO_NMAXFEATURE=25", cmake error "CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  lightweight_filtering/CMakeLists.txt:12 (pkg_check_modules)
"occurs

**Comment by hflemmen** [comment]
Seems like it can't find `kindr`. Did you install everything as described [here](https://github.com/ntnu-arl/rovtio#install-without-opengl-scene)?

**Comment by Pan-long-ming** [comment]
i have install the kindr ,like the fig
#
![2021-09-25 11-53-52 的屏幕截图](https://user-images.githubusercontent.com/72678161/134757058-2fa76fad-33d2-44b9-87b1-94fb2a6724ef.png)

**Comment by hflemmen** [comment]
I guess you [installed using cmake](https://github.com/ethz-asl/kindr#building)? Did you get any errors when you ran `sudo make install`?

To be honest, I have not tried this since I am [building it using catkin](https://github.com/ethz-asl/kindr#building-with-catkin).

**Comment by Pan-long-ming** [comment]
Thanks,it works when  i rebuilded it using catkin,and putted the code and kindr in the same src file.

**Comment by Pan-long-ming** [comment]
Thanks your open source,it will help me a lot.I want do some research about the thermal Odometry, Can you leave me your contact details,such as email? May be we can communicate about it.

**Comment by hflemmen** [comment]
Excellent. then I assume that it needs to be installed with `catkin` to work.

Sure. You can reach me at henrikdf at stud dot ntnu dot no.

**Comment by Pan-long-ming** [comment]
Is "henrikdf at stud dot ntnu dot no" your email? why  i can't find it

**Comment by hflemmen** [comment]
Yes, "henrikdf at stud dot ntnu dot no" is the email address. Replace "at" with "@" and "dot" with ".". I wrote it like that to avoid spambots crawling the public internet to recognize it.

**Comment by Pan-long-ming** [comment]
Thanks ,i have sent a email to you from 2060325004@email.szu.edu.cn

**Comment by Pan-long-ming** [comment]
Do you receive my email,which address is 2060325004@email.szu.edu.cn

**Comment by hflemmen** [comment]
Yes, I answered now.
