### ISSUE TITLE
Inquiries about sensor specifications

### ISSUE THREAD

**Issue by MobilityAI** [ntnu-arl/rovtio#4]
Thank you very much for uploading data to Google Drive.

I have a few questions about utilizing the data.

Is the unit of Angular Velocity in IMU degree/sec?

Is the sampling unit about 200 HZ right?

What is the sampling unit for each camera?

please answer about my question.

**Comment by hflemmen** [comment]
Hi!

No, it is radians/sec.

Correct, it is 200 Hz.

Thermal camera: 30 Hz
Visual camera: 20 Hz
(They are not synchronized, but software timestamped to the same clock.)

Hope this helps. :)
