### ISSUE TITLE
Second Questions

### ISSUE THREAD

**Issue by MobilityAI** [ntnu-arl/rovtio#5]
Thank you very much for last answers.

In the process of working with the data in Matlab, there were several informations I needed to know, so I asked another question.

1.  In the last answer, time synchronization between sensors was not done, but I am confused about what it means that synchronization is done in software. Do thermal image timestamps need to be calibrated or are they already processed in the data?

**Comment by hflemmen** [comment]
Hi!

I mean that the thermal camera and the visual camera are not synchronized in the sense that they trigger simultaneously. 

It was a clumsy formulation from me, but I meant that they are referenced to the same clock. I.e. the timestamps for the visual and thermal cameras follow the same timeline.
