### ISSUE TITLE
Question about Ground Truth

### ISSUE THREAD

**Issue by MobilityAI** [ntnu-arl/rovtio#6]
hello,

I'd like to compare the value estimated by the filter I developed from the data set you uploaded with the true value.

Although the topic '/aft_mapped_to_init_CORRECTED' is mentioned as an near ground true value estimated from LOAM, could  the ground truth obtained from the vicon tracking system also be read from the ROSBAG file?

Thanks for the previous answers.

**Comment by hflemmen** [comment]
Hi,

We don't remember exactly and I no longer have the setup we used, so I apologize that I can't answer your question.

However, since it is a well-posed problem for LOAM, we expect it to be more than sufficient to act as ground truth to test visual/thermal-inertial algorithms.

**Comment by MobilityAI** [comment]
Hi,

I checked the thesis out, and understood your answers

Thanks a lot!

**Comment by hflemmen** [comment]
Hi again,

Answering your other question I stumbled upon the topic `/vicon/charlie/charlie`. It contains ground truth from a highly accurate vicon optical tracking system for parts of the trajectory. Sorry for not mentioning it earlier.
