### ISSUE TITLE
Question about available frames in ROSBAG of Dataset

### ISSUE THREAD

**Issue by MobilityAI** [ntnu-arl/rovtio#7]
Hello,

I have a question because I am confused while using data set sync.

1. Is the topic "/aft_mapped_to_init_CORRECTED" pose set the reference frame to 'world' or "/aft_mapped_to_init_CORRECTED" ?
2. Can I use the topic "TF" as a true value to compare against an estimate?

please answer about my question.

**Comment by hflemmen** [comment]
Hi,

1. Yes, it is the pose referenced to `world`.
2. I am not quite sure what you mean. You can compare the pose you estimate to the pose from `/aft_mapped_to_init_CORRECTED`, which may be defined from the transforms in `/tf`.
