### ISSUE TITLE
Is it possible use ROTIO only? 

### ISSUE THREAD

**Issue by jonathansel** [ntnu-arl/rovtio#8]
Hi! 

Is it possible to use only 14-bit thermal images with this package? (i.e. ROTIO)

**Comment by hflemmen** [comment]
Hi!

Yes, it is. If you set the number of cameras to 1, and configure camera0(and all the other parameters that index a camera) to your thermal camera, it should work. It will automatically detect that it is a thermal camera based on the bit depth of the incoming image.
- Compile with `-DROVIO_NCAM=1`
- Set `camera_topic0` and `camera0_config` in the [launch](https://github.com/ntnu-arl/rovtio/blob/main/launch/rovtio.launch) file.
- You need to set the [config parameters](https://github.com/ntnu-arl/rovtio/blob/main/cfg/rovtio/rovtio.info) for camera0(I.e. every parameter that is postfixed with a "0") to correspond to thermal cameras. If you don't have them, the current parameters for camera1 are probably an ok initial guess, with the notable exception of the extrinsics, which you need to provide.

**Comment by hflemmen** [comment]
Did it work?

**Comment by jonathansel** [comment]
Hi!

Sorry for the late reply, I was away for a while. But I just gave it a try and it worked, thank you very much for the detailed reply.
